/* Generated By:JavaCC: Do not edit this line. AssetPathCompilerConstants.java */
package daris.plugin.asset.path;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssetPathCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int CID = 6;
  /** RegularExpression Id. */
  int XVALUE = 7;
  /** RegularExpression Id. */
  int PVALUE = 8;
  /** RegularExpression Id. */
  int RVALUE = 9;
  /** RegularExpression Id. */
  int REPLACE = 10;
  /** RegularExpression Id. */
  int JOIN = 11;
  /** RegularExpression Id. */
  int OPT = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int POSITIVE_INTEGER = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int SLASH = 18;
  /** RegularExpression Id. */
  int OR = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"cid\"",
    "\"xvalue\"",
    "\"pvalue\"",
    "\"rvalue\"",
    "\"replace\"",
    "\"join\"",
    "\"opt\"",
    "<STRING>",
    "<POSITIVE_INTEGER>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"/\"",
    "\"|\"",
    "\"-\"",
  };

}
